coverage:
  status:
    project: off
    # https://docs.codecov.com/docs/commit-status#patch-status
    patch:
      default:
        target: 80%
        informational: true
        if_ci_failed: error
comment:                  # this is a top-level key
  layout: "header, files, footer" # remove "new" from "header" and "footer"
  hide_project_coverage: false # set to false
