apiVersion: v1
kind: Service
metadata:
  name: openeuler-service
  labels:
    app: openeuler-service
    service: openeuler-service
spec:
  selector:
    app: openeuler
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openeuler-v1
  labels:
    app: openeuler
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openeuler
      version: v1
  template:
    metadata:
      labels:
        app: openeuler
        version: v1
    spec:
      containers:
      - name: openeuler
        image: openeuler-20.03-lts-sp1:latest
        command: ["/sbin/init"]
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 1024Mi
          requests:
            cpu: "2"
            memory: 1024Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openeuler-v2
  labels:
    app: openeuler
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openeuler
      version: v2
  template:
    metadata:
      labels:
        app: openeuler
        version: v2
    spec:
      containers:
      - name: openeuler
        image: openeuler-20.03-lts-sp1:latest
        command: ["sbin/init"]
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 1024Mi
          requests:
            cpu: "2"
            memory: 1024Mi
